//
// Created by piotr on 07/10/2021.
//

#ifndef WOLFRAM_AUTOMATA_WOLFRAMS_AUTOMATA_H
#define WOLFRAM_AUTOMATA_WOLFRAMS_AUTOMATA_H

class WolframAutomata {

};

#endif // WOLFRAM_AUTOMATA_WOLFRAMS_AUTOMATA_H
